### ISSUE TITLE
Add the lat/lon edit fields in Knack

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-geospatial-knack-ui#27]

**Comment by mateoclarke** [comment]
Either to the Location Details page or in a new Edit Locations page.

**Comment by johnclary** [comment]
@mateoclarke @mddilley 

Here's the new/final app env for you to develop on:
https://builder.knack.com/atd/signs-markings#pages/scene_1028

Work Order Details Page
Scene: scene_1028
New location view: view_2607
Live example: https://atd.knack.com/signs-markings#work-order--signs/view-work-orders-sign-details/5d13bb70d3186524eaf1e38d/

Location Details Page
Scene: scene_1039
Location details view: view_2609
Live Example: https://atd.knack.com/signs-markings#work-order--signs/view-work-orders-sign-details/5d13bb70d3186524eaf1e38d/view-work-order-signs-location-details/5d13bb70d3186524eaf1e3a7/

Edit Location Page
Scene: scene_1040
View: view_2612
Live Example: https://atd.knack.com/signs-markings#work-order--signs/view-work-orders-sign-details/5d13bb70d3186524eaf1e38d/edit-work-order-signs-location/5d13bb70d3186524eaf1e3a7/
