### ISSUE TITLE
Handle success and errors of post to Knack API

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-geospatial-knack-ui#7]
Handle success and errors of Knack API req after data submission.

Does redirect happen upon success? How is error displayed to user?

**Comment by amenity** [comment]
Won't be necessary if we're able to embed app.

**Comment by mateoclarke** [comment]
This is unneeded now that we can use window.postMessage to communicate values between the parent Knack app and the embedded React iframe.
