### ISSUE TITLE
Change the tiles of the map to satellite tiles

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-geospatial-knack-ui#9]
In order to display a more familiar view to user, change the tiles of the map from street view to satellite view.

**Comment by johnclary** [comment]
Or, even better—have a basemap selector for street map or satellite imagery, or a hybrid

**Comment by amenity** [comment]
@johnclary - send Mike link to ESRI hosted basemaps.

**Comment by johnclary** [comment]
@mddilley here's one of our Esri-hosted basemaps:
http://www.arcgis.com/home/item.html?id=ce80064660bd495d86be81f390979b59

Let me know if I can help you research this.
